language: node_js
node_js: 12
services:
  - docker

before_install:
  - docker build -t margaritachepikova/production-flow -f Dockerfile.dev .

script:
  - docker run -e CI=true margaritachepikova/production-flow npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "production-flow"
  env: "ProductionFlow-env"
  bucket_name: "elasticbeanstalk-us-east-2-380182177737"
  bucket_path: "production-flow"
  on:
    branch: main
  access_key_id:
    secure: "vkFkAirHZpoUfHg+KZIPJOelFyKjzDj5EpntW3EEJSxjjv6MsJDotIvpOEv2l9lkEVbt92Xm17Vf5UgbIy+JJnjqW15UH02wEjUzdT+jyjtdYHddKff6I8ch/R8LTgDY6Jmdilaaib0Vw3eGVvKvozXBVVBsQZgg+ReO9iZILpY+wztAySSSm33gs+1JdpEMiWa/QAr3+dbMFw8CWWoVDd8euWXos7G8c2P3ZEmWXhgXViB8ZSpKmQlwyWAnkv4p6jnPerM3ZbGHe/FjnDyAN4pNzEtxWMdehIcct79AmtpI3fWzzQ570BoirBJKlY90ycN9pXEJ8CP075M/oI37PVZQuY3WhbA4UZZiS3xye8yIcxJw1EtPuJxSFAwvIoihQwEVMNZCL/phfZfGeFktEOLOPMI9Q3ZcYoD2/6gcRzWMc+8FKWBb9R87TShmbR0NdGTYC0sz0a8OaJTVXnZNKlx1DhnKkoH3ggKLQfXV516llMGRTKkz1qSNkmQe406E2++Li2bgGDVtlx4jdKQASDSOMzlleKUfn7aATH0dOQai/t5LUUdHcUsIAu9bgQGxnZ+pKM+tHuBHJtQyohX7GYreYztOQ+ZoAUlyYnp2s+R7fqhO+F3IVgyXAISI384HxEBvhvXNiH6m2Ynq2X72/jNZf6dFbYcexfALXQpW0to="
  secret_access_key:
    secure: "05beUoX3SQbf99P33/hO0hFJYzgcETg3Db7i4ULBTCuhIH9Xjfvy6jidZOCQQmJ31ZOgGadz28d3YQhauGQuX59mVyqIEycy83qGNNlAOizD2g9KWFEEGvwS76FIZNvFApCQXiA3dix6K9xNG8SSG9xWeyVBYXgalppUwGI5lTCTmhcTfpZdADRCujS8mwqtHD1ZfHX+quObwcShCyl5mCBqsRhdEcwBRBzOqdvnaEu0SjaQ4b9RANwz16dAaY+1Q3qRQ6c4NZiDbLj4BCWx7fP0SYavB4YoODWcZcdvOWacMGH7xFjhtRE8NWo041jBGMUsVzlF0yShbd8syFT2+RkAaQ+J68bu3KZBh+KNx1QoDx6+xP1Xvpom62zRBsd6/Z9/7SQ6LkMLaLMbhKubWVr3BqqQqJ4LS50Rdlwnfh/gIp5z9HPyAZ1xhdxetEZ4qVJZT8TNnJm/p3U7dW0R4+4ZgCntun78IJI7AZvVEN9hGEpsqbF5ZNTodEgNdyiCEODHKsmMVEPfb8hKR4SiUz5I8HjzXQsPaphkbTu7GjyNBmIB11Pbs8k8mXi6xpxNBrz/tKwXymqJqxFPsVLivD0+G6YX9KSR5pGGoEgzDjQV7z0xesfRF13xI8dGm+KVZelKFwFAmSYMvpVXB7KVh1X4c6yoarY9/roYZzgr4FU="
