language: node_js
node_js: 12
services:
  - docker

before_install:
  - docker build -t margaritachepikova/production-flow -f Dockerfile.dev .

script:
  - docker run -e CI=true margaritachepikova/production-flow npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "production-flow"
  env: "ProductionFlow-env"
  bucket_name: "elasticbeanstalk-us-east-2-380182177737"
  bucket_path: "production-flow"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
