language: node_js
node_js: 12
services:
  - docker

before_install:
  - docker build -t margaritachepikova/production-flow -f Dockerfile.dev .

script:
  - docker run -e CI=true margaritachepikova/production-flow npm run test -- --coverage